// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke%202.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/auth.ts";
import * as $4 from "./routes/echo/game.ts";
import * as $5 from "./routes/echo/wait.ts";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke%202.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/auth.ts": $3,
    "./routes/echo/game.ts": $4,
    "./routes/echo/wait.ts": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
